name: 'Setup Auto Linux'
description: 'Install Intuit Auto release management native binary'
inputs:
  version:
    description: 'Version of Auto'
    required: false
    default: 'latest'
  platform:
    description: 'Target platform'
    required: false
    default: 'linux'
    
branding:
  icon: 'box'  
  color: 'green'

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/install-${{ inputs.platform }}.sh
      shell: bash
      env:
        AUTO_VERSION: ${{ inputs.version }}
        AUTO_PLATFORM: ${{ inputs.platform }}
